@REM   WARNING   this file is automatically generated by RT-Druid

@REM   If you want modify this file, you should move it to a safe folder,
@REM   like the project's root, and update the path inside the project 
@REM   properties "C/C++ Make Project" -> "Build command"
@REM   i.e.   ${workspace_loc:stopwatch_autogen}/make_launcher.bat

@REM   Unset CWD and PWD. They may cause cygwin warning.
@set CWD=
@set PWD=

@set EE_BASH_PATH=C:\cygwin\bin\bash

@if EXIST %EE_BASH_PATH%.exe goto endok

@echo %EE_BASH_PATH% not found.

@echo Trying c:\cygwin\bin\bash.exe
@set EE_BASH_PATH=c:\cygwin\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo Trying c:\cygwin\usr\bin\bash.exe
@set EE_BASH_PATH=c:\cygwin\usr\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo Trying d:\cygwin\bin\bash.exe
@set EE_BASH_PATH=d:\cygwin\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo Trying d:\cygwin\usr\bin\bash.exe
@set EE_BASH_PATH=d:\cygwin\usr\bin\bash.exe
@if EXIST %EE_BASH_PATH% goto endok
@echo %EE_BASH_PATH% not found.

@echo ERROR: bash not found.
@echo Please check the location of your cygwin installation and enter it in Eclipse in "Windows/Preferences/RT-Druid/Cygwin paths".
@exit

:endok
@echo %EE_BASH_PATH% found!

@set ERIKA_FILES=C:\Users\Matteo\Desktop\Erika\eclipse\plugins\com.eu.evidence.ee_2.5.0.20150528_0935\ee_files

@%EE_BASH_PATH% -l -c "cd \"%CD%\"; make %1 %2 %3 %4 %5 %6 %7 %8 %9"
